# Quickstart Numpy.
This tutorial is from [this link](https://numpy.org/devdocs/user/absolute_beginners.html)

We import **Numpy**

In [75]:
import numpy as np

We can create arrays with np.array()

In [76]:
a = np.array([1, 2, 3, 4])
print(a)
print(a[0])

[1 2 3 4]
1


## How to create a basic array.

To create an array we can use multiple options:
- np.array
- np.zeros
- np.ones
- np.empty
- np.arange
- np.linspace

In [77]:
np.array([[1, 2, 3, 4],[3, 4, 5, 6]])

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [78]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [80]:
np.empty((2, 1))

array([[ 5.],
       [10.]])

In [81]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [82]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

## Adding, removing and sorting elements of an array.

We can sort or concatenate elements of an array with the next methods:
- np.sort()
- np.concatenate()

In [84]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a,b)))

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


We can concatenate by different axes or dimensions:

In [85]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
z = np.concatenate((x, y), axis = 0)
print(z)

[[1 2]
 [3 4]
 [5 6]]


## How do you know the shape and size of an array?
We can use:
- ndarray.ndim number of dimensions of the array
- ndarray.shape: tupple with the dim of each axis
- ndarray.size: number of total elements of the array

In [86]:
print(x.size)
print(x.shape)
print(x.ndim)

4
(2, 2)
2


## Can you reshape an array
We can reshape with **np.reshape** or ndarray.reshape() 

In [87]:
a = np.arange(6)
print(a)
b = np.reshape(a, newshape = (2, 3))
b = a.reshape(2, 3)
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


## How to convert an array of 1D to 2D.

We can do it with two manners: 
- np.newaxis
- np.expand_dims

In [88]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a2 = a[np.newaxis, :]
a3 = a[:, np.newaxis]
print(a2)
print(a2.shape)
print(a3.shape)
c = np.expand_dims(a, axis = 0)
print(c.shape)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
(1, 6)
(6, 1)
(1, 6)


## Indexing and slicing.

We have some examples:

In [89]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


We can visualize it this way:
![imagen](images/np_indexing.png)

If we wante to select values from your array that fulfill certain conditions,it's straightforfward with Numpy

In [68]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[a < 6])

We can select, for example, number that are equal to or greater than 5, and use that condition to index an array.

In [72]:
five_up = (a >= 5)
print(five_up)
print(a[five_up])

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]


We can select elements that are divisible by 2:

In [73]:
divisible_by_2 = a[a % 2 == 0]

In [74]:
print(divisible_by_2)

[ 2  4  6  8 10 12]
