# Quickstart Numpy.
This tutorial is from [this link](https://numpy.org/devdocs/user/absolute_beginners.html)

We import **Numpy**

In [2]:
import numpy as np

We can create arrays with np.array()

In [3]:
a = np.array([1, 2, 3, 4])
print(a)
print(a[0])

[1 2 3 4]
1


## How to create a basic array.

To create an array we can use multiple options:
- np.array
- np.zeros
- np.ones
- np.empty
- np.arange
- np.linspace

In [4]:
np.array([[1, 2, 3, 4],[3, 4, 5, 6]])

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [5]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [7]:
np.empty((2, 1))

array([[-5.73021895e-300],
       [ 8.04338871e-320]])

In [8]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

## Adding, removing and sorting elements of an array.

We can sort or concatenate elements of an array with the next methods:
- np.sort()
- np.concatenate()

In [11]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a,b)))

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


We can concatenate by different axes or dimensions:

In [12]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
z = np.concatenate((x, y), axis = 0)
print(z)

[[1 2]
 [3 4]
 [5 6]]


## How do you know the shape and size of an array?
We can use:
- ndarray.ndim number of dimensions of the array
- ndarray.shape: tupple with the dim of each axis
- ndarray.size: number of total elements of the array

In [13]:
print(x.size)
print(x.shape)
print(x.ndim)

4
(2, 2)
2


## Can you reshape an array
We can reshape with **np.reshape** or **ndarray.reshape()**: 

In [14]:
a = np.arange(6)
print(a)
b = np.reshape(a, newshape = (2, 3))
b = a.reshape(2, 3)
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


## How to convert an array of 1D to 2D.

We can do it with two manners: 
- np.newaxis
- np.expand_dims

In [15]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a2 = a[np.newaxis, :]
a3 = a[:, np.newaxis]
print(a2)
print(a2.shape)
print(a3.shape)
c = np.expand_dims(a, axis = 0)
print(c.shape)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
(1, 6)
(6, 1)
(1, 6)


## Indexing and slicing.

We have some examples:

In [16]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


We can visualize it this way:
![imagen](images/np_indexing.png)

If we wante to select values from your array that fulfill certain conditions,it's straightforfward with Numpy

In [17]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[a < 6])

We can select, for example, number that are equal to or greater than 5, and use that condition to index an array.

In [18]:
five_up = (a >= 5)
print(five_up)
print(a[five_up])

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]


We can select elements that are divisible by 2:

In [19]:
divisible_by_2 = a[a % 2 == 0]

In [20]:
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [21]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [22]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


We can use **_np.nonzero()_** to print indices of elements that are, for example, less than 5:

In [23]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In this example, a tuple of arrays was returned, one for each dimension. The firts array represents the row indices where the values are found, and the second array represents the columns.

If we want to generate a list of coordinates, we can zip the arrays, iterate over the list of coordinates and print them. For example:

In [24]:
list_of_coordinates = list(zip(b[0],b[1]))
print(list_of_coordinates)

[(0, 0), (0, 1), (0, 2), (0, 3)]


In [25]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


We can also use np.nonzero() to print the elements in an array that are less than 5:


In [26]:
print(a[b])

[1 2 3 4]


If the element you're looking for doesn't exist in the array, then the returned array of indices will be empty. For example:

In [27]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


## How to create an array from existing data.
We can easily create a new array from a section of an existing array

In [28]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can slice it:

In [29]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

We can stack two existing arrays in one, horizontally and vertically with:
- **np.vstack((,))**
- **np.hstack((,))**

In [30]:
a1 = np.array([[1,1],
               [2,2]])

In [31]:
a2 = np.array([[3,3],
               [4,4]])

In [32]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [33]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

We can split an array into several smaller arrays using **hsplit**. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

In [34]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

If we want to split this array into three equally shaped arrays, we would run:

In [35]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

If we wanted to split this array into three equally shaped arrays, we would run:

In [36]:
np.hsplit(x,(3,6,8))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8],
        [19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

We can use the **view** method to create a new array objetct that looks at the same data as the original array (a shallow copy). Views are an important NumPy concept. NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it's importante to be aware of this -**modify data in a view also modifies the original array!**

Now we create an array **b1** by slicing **a** and modify the corresponding element in **a** as well.

In [37]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0]
b1

array([1, 2, 3, 4])

In [38]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [39]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

With copy method well make a complete copy of the array and its data (a deep copy). If we modify b2, we will not modify a

In [40]:
b2 = a.copy()
b2
b2[0,0] = 1
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

 # Basic array operations.
This section covers addition, subtraction, multiplication, division and more.


In [42]:
data = np.array([1, 2])
ones = np.ones(2, dtype = int)
data + ones

array([2, 3])

In [43]:
data - ones

array([0, 1])

In [44]:
data * ones

array([1, 2])

In [45]:
data / data

array([1., 1.])

Basic operations are simple with NumPy. If you want to find the sum of the elements in an array , you'd use **sum()**. THis works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [46]:
a = np.array([1, 2, 3, 4])

In [47]:
a.sum()

10

If we start with this array:

In [48]:
b = np.array([[1, 1], [2, 2]])

We can sum over the axis of rows or columns:

In [49]:
b.sum(axis = 0)

array([3, 3])

In [50]:
b.sum(axis = 1)

array([2, 4])

## Broadcasting

The multiplication of each cell it's called **broadcasting**. 

In [51]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

 ## More useful array operations

This section covers maximum, minimum, sum, mean, product, stardardd deviation, and more.

In [52]:
data.max()

2.0

In [53]:
data.min()

1.0

In [54]:
data.sum()

3.0

Let's start with this array, called a:

In [55]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],

              [0.54627315, 0.05093587, 0.40067661, 0.55645993],

              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])


By default, every NumPy aggregation function will return the aggregate of the entire array. To find the sum or the minimum of the elements in our array, run:

In [56]:
a.sum()

4.8595784

In [57]:
a.min()

0.05093587

We can specify on which axis we want the aggregation function to be computed.

In [58]:
a.sum(axis = 0)

array([1.12378257, 1.04875507, 1.01034462, 1.67669614])

In [59]:
a.sum(axis = 1)

array([1.51832856, 1.55434556, 1.78690428])

In [60]:
a.max(axis = 0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

# Creating matrices.

We can pass Python lists of list to create a 2-D array to represent them in Numpy.

In [61]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data 

array([[1, 2],
       [3, 4],
       [5, 6]])

Indexing and slicing operations are useful when we're manipulating matrices:

In [62]:
data[0, 1]

2

In [63]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [64]:
data[2]

array([5, 6])

In [65]:
data[0:2,0]

array([1, 3])

![imagen_matrices](images/np_matrix_indexing.png)

We can aggregate all the values in a matrix and we can aggregate them across columns or rows using the **axis** parameter:

In [66]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [67]:
data.max()

6

In [68]:
data.min()

1

In [69]:
data.max(axis = 0)

array([5, 6])

In [70]:
data.max(axis = 1)

array([2, 5, 6])

In [71]:
data.min(axis = 0)

array([1, 2])

In [72]:
data.max(axis = 1)

array([2, 5, 6])

Remember:
- axis = 0: rows
- axis = 1: columns

Once we've created our matrices, we can add and multiply them using arithmetic opertators if we have two matrices that are the same size.

In [73]:
data = np.array([[1, 2], [3, 4]])
ones = np.ones([2,2], dtype = int)
ones

array([[1, 1],
       [1, 1]])

In [74]:
data + ones

array([[2, 3],
       [4, 5]])

We can do arithmetic operations on matrices of different sizes,  but only if one matrix has only one column or one row. In this case, Numpy will use its bradcast rules for the operation.

In [79]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [84]:
np.ones((2,3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

Thera are often instances where we want NumPy to initialize the values of an array. NumPy offers functions like **ones()** and **zeros()**, and the **random.Generator** class for random number generation for that.

In [85]:
np.ones(2)

array([1., 1.])

In [88]:
np.zeros(3)

array([0., 0., 0.])

In [95]:
rng = np.random.default_rng?

In [135]:
rng = np.random.default_rng(3)

In [139]:
rng.random(4)

array([0.43062802, 0.58679857, 0.73783779, 0.95626725])

We can also use **ones()**, **zeros()**, and **random()** to create a 2D array if we give them a tuple describing the dimensions of the matrix.

In [156]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [157]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [158]:
rng.random((2, 3, 2))

array([[[0.62369273, 0.60688379],
        [0.97055876, 0.78703271],
        [0.78991748, 0.05409376]],

       [[0.36928631, 0.08489477],
        [0.19352758, 0.21386699],
        [0.85864193, 0.12675498]]])

## Generating random numbers.


THe use of random number generation is an important part of the configuration and evaluation of many numerical and machine learning algorithms. Wheter you need to randomly initialize weighs in a neural network, split data into random setsk, or randomly shuffle your dataset, being able to generate random numbers (actaully, repeatable pseudo-random numbers) is essental

With **Generator.integers**, you can generate random integers form low (remember taht is inclusive with NumPy) to high (exclusive). We can set **endpoint = True** to make the high number inclusive.

We can generate a 2 x 4 array of random integers between 0 and 4 with:

In [150]:
rng.integers(10, size=(2,4))

array([[6, 8, 1, 2],
       [5, 5, 3, 3]])

In [151]:
rng.integers?

In [153]:
rng.integers(low = 0,high = 100, size = (1, 5))

array([[18,  4, 74, 18, 75]])

In [159]:
rng.random((2,2))

array([[0.29675777, 0.49284698],
       [0.84946041, 0.96523142]])

## How to get unique items and counts.

In this section we will cover **np.unique()**.

In [160]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [162]:
np.unique?

To get the indices of unique values in a NumPy array (an array of first index positions of unique values in the array), just pass the **return_index** argument in **np.unique()** as well as your array.

In [172]:
np.unique?

In [166]:
u, indices = np.unique(a, return_index = True)
# unique and sorted
print(u)
print(indices)

[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]


We can pass the **return_counts** argument in **np.unique()** along with our array to get the frequency count of unique values in a NumPy array.

In [168]:
unique_values, occurrence_count = np.unique(a, return_counts = True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


This also works with 2D arrays:

In [169]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [177]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


If the axis argument isn't passed, our 2D array will be flattened. If we want to get the unique rows or columns, make sure to pass **axis** argument:

In [181]:
unique_rows = np.unique(a_2d, axis = 0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Transposing and reshaping a matrix.

This section covers **arr.reshape()**, **arr.transpose()**, **arr.T**