# Quickstart Numpy.
This tutorial is from [this link](https://numpy.org/devdocs/user/absolute_beginners.html)

We import **Numpy**

In [2]:
import numpy as np

We can create arrays with np.array()

In [3]:
a = np.array([1, 2, 3, 4])
print(a)
print(a[0])

[1 2 3 4]
1


## How to create a basic array.

To create an array we can use multiple options:
- np.array
- np.zeros
- np.ones
- np.empty
- np.arange
- np.linspace

In [4]:
np.array([[1, 2, 3, 4],[3, 4, 5, 6]])

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [5]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [7]:
np.empty((2, 1))

array([[-5.73021895e-300],
       [ 8.04338871e-320]])

In [8]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

## Adding, removing and sorting elements of an array.

We can sort or concatenate elements of an array with the next methods:
- np.sort()
- np.concatenate()

In [11]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a,b)))

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


We can concatenate by different axes or dimensions:

In [12]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
z = np.concatenate((x, y), axis = 0)
print(z)

[[1 2]
 [3 4]
 [5 6]]


## How do you know the shape and size of an array?
We can use:
- ndarray.ndim number of dimensions of the array
- ndarray.shape: tupple with the dim of each axis
- ndarray.size: number of total elements of the array

In [13]:
print(x.size)
print(x.shape)
print(x.ndim)

4
(2, 2)
2


## Can you reshape an array
We can reshape with **np.reshape** or **ndarray.reshape()**: 

In [14]:
a = np.arange(6)
print(a)
b = np.reshape(a, newshape = (2, 3))
b = a.reshape(2, 3)
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


## How to convert an array of 1D to 2D.

We can do it with two manners: 
- np.newaxis
- np.expand_dims

In [15]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a2 = a[np.newaxis, :]
a3 = a[:, np.newaxis]
print(a2)
print(a2.shape)
print(a3.shape)
c = np.expand_dims(a, axis = 0)
print(c.shape)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
(1, 6)
(6, 1)
(1, 6)


## Indexing and slicing.

We have some examples:

In [16]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


We can visualize it this way:
![imagen](images/np_indexing.png)

If we wante to select values from your array that fulfill certain conditions,it's straightforfward with Numpy

In [17]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[a < 6])

We can select, for example, number that are equal to or greater than 5, and use that condition to index an array.

In [18]:
five_up = (a >= 5)
print(five_up)
print(a[five_up])

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]


We can select elements that are divisible by 2:

In [19]:
divisible_by_2 = a[a % 2 == 0]

In [20]:
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [21]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [22]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


We can use **_np.nonzero()_** to print indices of elements that are, for example, less than 5:

In [23]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In this example, a tuple of arrays was returned, one for each dimension. The firts array represents the row indices where the values are found, and the second array represents the columns.

If we want to generate a list of coordinates, we can zip the arrays, iterate over the list of coordinates and print them. For example:

In [24]:
list_of_coordinates = list(zip(b[0],b[1]))
print(list_of_coordinates)

[(0, 0), (0, 1), (0, 2), (0, 3)]


In [25]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


We can also use np.nonzero() to print the elements in an array that are less than 5:


In [26]:
print(a[b])

[1 2 3 4]


If the element you're looking for doesn't exist in the array, then the returned array of indices will be empty. For example:

In [27]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


## How to create an array from existing data.
We can easily create a new array from a section of an existing array

In [28]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can slice it:

In [29]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

We can stack two existing arrays in one, horizontally and vertically with:
- **np.vstack((,))**
- **np.hstack((,))**

In [50]:
a1 = np.array([[1,1],
               [2,2]])

In [51]:
a2 = np.array([[3,3],
               [4,4]])

In [52]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [53]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

We can split an array into several smaller arrays using **hsplit**. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

In [54]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

If we want to split this array into three equally shaped arrays, we would run:

In [55]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

If we wanted to split this array into three equally shaped arrays, we would run:

In [56]:
np.hsplit(x,(3,6,8))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8],
        [19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

We can use the **view** method to create a new array objetct that looks at the same data as the original array (a shallow copy). Views are an important NumPy concept. NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it's importante to be aware of this -**modify data in a view also modifies the original array!**

Now we create an array **b1** by slicing **a** and modify the corresponding element in **a** as well.

In [89]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0]
b1

array([1, 2, 3, 4])

In [90]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [91]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

With copy method well make a complete copy of the array and its data (a deep copy). If we modify b2, we will not modify a

In [92]:
b2 = a.copy()
b2
b2[0,0] = 1
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

 # Basic array operations.
This section covers addition, subtraction, multiplication, division and more.


In [94]:
data = np.array([1, 2])
ones = np.ones(2, dtype = int)
data + ones

array([2, 3])

In [95]:
data - ones

array([0, 1])

In [96]:
data * ones

array([1, 2])

In [97]:
data / data

array([1., 1.])

Basic operations are simple with NumPy. If you want to find the sum of the elements in an array , you'd use **sum()**. THis works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [98]:
a = np.array([1, 2, 3, 4])

In [99]:
a.sum()

10

If we start with this array:

In [100]:
b = np.array([[1, 1], [2, 2]])

We can sum over the axis of rows or columns:

In [101]:
b.sum(axis = 0)

array([3, 3])

In [102]:
b.sum(axis = 1)

array([2, 4])

## Broadcasting

The multiplication of each cell it's called **broadcasting**. 

In [103]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

 ## More useful array operations

This section covers maximum, minimum, sum, mean, product, stardardd deviation, and more.

In [104]:
data.max()

2.0

In [105]:
data.min()

1.0

In [108]:
data.sum()

3.0

Let's start with this array, called a:

In [109]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],

              [0.54627315, 0.05093587, 0.40067661, 0.55645993],

              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])


By default, every NumPy aggregation function will return the aggregate of the entire array. To find the sum or the minimum of the elements in our array, run:

In [110]:
a.sum()

4.8595784

In [111]:
a.min()

0.05093587

We can specify on which axis we want the aggregation function to be computed.

In [115]:
a.sum(axis = 0)

array([1.12378257, 1.04875507, 1.01034462, 1.67669614])

In [116]:
a.sum(axis = 1)

array([1.51832856, 1.55434556, 1.78690428])

In [117]:
a.max(axis = 0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

# Creating matrices.

We can pass Python lists of list to create a 2-D array to represent them in Numpy.

In [119]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data 

array([[1, 2],
       [3, 4],
       [5, 6]])

Indexing and slicing operations are useful when we're manipulating matrices:

In [120]:
data[0, 1]

2

In [121]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [123]:
data[2]

array([5, 6])

In [124]:
data[0:2,0]

array([1, 3])

![imagen_matrices](images/np_matrix_indexing.png)

We can aggregate all the values in a matrix and we can aggregate them across columns or rows using the **axis** parameter:

In [125]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [126]:
data.max()

6

In [127]:
data.min()

1

In [128]:
data.max(axis = 0)

array([5, 6])

In [131]:
data.max(axis = 1)

array([2, 5, 6])

In [132]:
data.min(axis = 0)

array([1, 2])

In [133]:
data.max(axis = 1)

array([2, 5, 6])

Remember:
- axis = 0: rows
- axis = 1: columns

Once we've created our matrices, we can add and multiply them using arithmetic opertators if we have two matrices that are the same size.